import Image from "next/image";
import Link from "next/link";
import styles from "./footer.module.css";

export default async function Footer() {
    return (
        <footer className={styles.footer}>
            <small>
                Made with{" "}
                <Image
                    src="/img/heart.svg"
                    alt="love"
                    width={16}
                    title="love"
                    height={16}
                ></Image>{" "}
                and{" "}
                <Image
                    src="/img/chatgpt.svg"
                    alt="ChatGPT"
                    title="ChatGPT"
                    width={18}
                    height={18}
                ></Image>{" "}
                by{" "}
                <a
                    href="https://github.com/Khajiitos"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Khajiitos
                </a>
            </small>

            <small>
                Designed by a{" "}
                <a
                    href="https://github.com/sutaC"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    sutaC
                </a>
            </small>

            <small>
                Content generated by AI, don&apos;t take everything seriously!
            </small>
        </footer>
    );
}
