import Image from "next/image";
import Link from "next/link";

export default async function Footer() {
    return (
        <footer>
            <p>
                Made with{" "}
                <Image
                    src="/img/heart.svg"
                    alt="love"
                    width={16}
                    title="love"
                    height={16}
                ></Image>{" "}
                and{" "}
                <Image
                    src="/img/chatgpt.svg"
                    alt="ChatGPT"
                    title="ChatGPT"
                    width={18}
                    height={18}
                ></Image>{" "}
                by <Link href="https://github.com/Khajiitos">Khajiitos</Link>
            </p>
            <p>
                Designed by <Link href="https://github.com/sutaC">sutaC</Link>
            </p>
            <p>
                Content generated by AI, don&apos;t take everything seriously!
            </p>
        </footer>
    );
}
